# Generated by Django 5.1.7 on 2025-03-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstalledModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('landing_url', models.CharField(blank=True, max_length=255)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
