# Generated by Django 4.2.20 on 2025-03-22 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modular_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installedmodule',
            name='landing_url',
            field=models.CharField(max_length=100),
        ),
    ]
